# Generated by Django 4.1.1 on 2022-12-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_remove_user_is_active_user_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.IntegerField(choices=[(2, "Teacher"), (1, "User")]),
        ),
    ]
