# Generated by Django 4.1.1 on 2022-12-08 10:33

import account.models
from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "role",
                    models.IntegerField(
                        choices=[(4, "Admin"), (2, "Teacher"), (1, "User")]
                    ),
                ),
                (
                    "grade",
                    models.IntegerField(
                        choices=[
                            (0, "None"),
                            (1, "Ebtedaie"),
                            (2, "Motevasete"),
                            (3, "Karshenasi"),
                            (4, "Arshad"),
                            (5, "Phd"),
                        ]
                    ),
                ),
                ("created_at", django_jalali.db.models.jDateField(auto_now_add=True)),
                ("updated_at", django_jalali.db.models.jDateField(auto_now=True)),
                ("is_active", models.BooleanField(default=False)),
                ("user_name", models.CharField(max_length=33)),
                (
                    "phone",
                    models.CharField(
                        max_length=17,
                        unique=True,
                        validators=[account.models.phone_validator],
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
