# Generated by Django 4.1.1 on 2022-12-08 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_active",
        ),
        migrations.AddField(
            model_name="user",
            name="state",
            field=models.IntegerField(
                choices=[(0, "Suspend"), (1, "Active"), (2, "Reported"), (3, "Banned")],
                default=0,
            ),
        ),
    ]
